use_frameworks!

target 'DLCharts_Example' do
    pod 'DLCharts', :path => '../'
#  pod 'DLCharts', :podspec => '../DLCharts.podspec'  # 指定podspec文件
   pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git'

end
